### ISSUE TITLE
Link to SEP-8 error when the message Error code 'op_no_trust' is thrown in SEP-08 Send action

### ISSUE THREAD

**Issue by shanzzam** [stellar/stellar-demo-wallet#201]
I was doing a SEP-08 Send action and encountered a no_op_trust after verifying the sandwiched transaction.
We'll want to create a way to link to the error. This looks like the error https://developers.stellar.org/api/errors/result-codes/operation-specific/allow-trust/ `op_no_trustline` even though I see in [code](https://github.com/shanzzam/go/blob/master/services/horizon/internal/codes/main.go) it's the string `op_no_trust`.

**Comment by marcelosalloum** [comment]
I think the main issue here is the error code `op_no_trust` was missing from the map of error codes:
https://github.com/stellar/stellar-demo-wallet/blob/790e8ba3812ee9bb5ebf73ffbce19f8ea2e674b8/src/helpers/getErrorString.ts#L7-L30

I'm adding that code to the map in https://github.com/stellar/stellar-demo-wallet/pull/202.

That's different from what the issue proposes but addresses the root cause, I think? 
If we still want to add links to the error alerts, that won't be so trivial because we would need to create a more complex component and error handling structure to support texts with links. Let me know what you think.

**Comment by shanzzam** [comment]
This is looks good. We'll address adding links to errors after release 1.2.1
